### ISSUE TITLE
models

### ISSUE THREAD

**Issue by denghan6688** [sheelabhadra/Learning2Drive#1]
May I ask if you have any trained models to share for me, I would appreciate it

**Comment by sheelabhadra** [comment]
Hi @denghan6688, sorry for the slow reply. I trained my model on a custom track which no pedestrians, cars, or intersections. So, it won't work well in the default towns provided in CARLA. I have updated the instructions for the training procedure in the readme file. Hopefully, that will make it easier to train your own model on whatever track you are running your experiments on.
