### ISSUE TITLE
About the Data Image 

### ISSUE THREAD

**Issue by HaoranTang** [sheelabhadra/Learning2Drive#10]
Hi, I am reproducing your code for practice, can I know what are the data images like? Are they just screenshots of my simulation window (for the current carla, just press R to record the third-person driving scene as image), or I have to use the build-in recorder to record everything as a log such as accelerations and orientations? Attached is a screenshot, is this what a data image supposed to be? Thank you so much in advance!
![00007740](https://user-images.githubusercontent.com/46015479/160744783-a2aebbbf-e55a-45b3-81eb-e867ad671a85.png)

**Comment by sheelabhadra** [comment]
Hi @HaoranTang, I used an older version of Carla and the images I used were captured by a first-person camera attached to the car. These are pretty straightforward to obtain in the new version as mentioned [here](https://carla.readthedocs.io/en/0.9.2/python_api_tutorial/#sensors).

**Comment by HaoranTang** [comment]
Hi @sheelabhadra, thank you for the help!
